services:
  - type: web
    name: kraken-bot
    env: python
    plan: free
    branch: main
    buildCommand: ""
    startCommand: ./start.sh
    runtime: python
    pythonVersion: 3.10.13
    envVars:
      - key: API_TOKEN
        value: ВСТАВЬ_СВОЙ_ТОКЕН_СЮДА
